name: 'Deploy to Heroku' #set whatevername you want to your github job
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0  # use the latest version of the action
        with:
          email: alex1dre.girard@gmail.com # your heroku email
          api_key: 6bff9ddc-7993-4e07-8030-1d6b3d05b35a # your  heroku api key
          app_name: marvel-react-sample # you aplication name
          dockerfile: './dockerfile' # set the path to the folder wher the Dokerfile is located